export const michaelScott: string[] = [
  "Would I rather be feared or loved? Easy. Both. I want people to be afraid of how much they love me.",
  "I saved a life. My own. Am I a hero? I really can't say, but yes!",
  "No, I'm not going to tell them about the downsizing. If a patient has cancer, you don't tell them.",
  "Do I have a special someone? Well, yeah, of course. A bunch of 'em. My employees.",
  "They say on your deathbed you never wish you spent more time at the office — but I will.",
  "Make friends first, make sales second, make love third. In no particular order.",
  "I love inside jokes. I hope to be a part of one someday.",
  "I'm an early bird and a night owl. So I'm wise and have worms.",
  "I wanna be married and have 100 kids so I can have 100 friends and no one can say 'no' to being my friend.",
  "I feel like all my kids grew up and then they married each other. It's every parent's dream.",
  "You know what they say 'Fool me once, strike one, but fool me twice… strike three.",
  "I know it's illegal in Pennsylvania, but it's for charity, and I consider myself a great philanderer.",
  "Two queens at casino night. I am gonna drop a deuce on everybody.",
  "I don't understand. We have a day honoring Martin Luther King, but he didn't even work here.",
  "I'm not superstitious but I am a little stitious.",
  "And I'm optimistic because every day I get a little more desperate.",
  "I am Beyonce, always.",
  "It's not like booze ever killed anyone.",
  "And I knew exactly what to do. But in a much more real sense, I had no idea what to do.",
  "The worst thing about prison was the dementors.",
  "There's no such thing as an appropriate joke. That's why it's called a joke.",
  "I say dance, they say 'How high?'",
  "Tell him to call me ASAP as possible.",
  "Dwight, you ignorant slut.",
  "I want you to rub butter on my foot… Pam, please? I have Country Crock.",
  "About 40 times a year, Michael gets sick but has no symptoms. Dwight is always gravely concerned.",
  "Any man who says he totally understands women is a fool. Because they are un-understandable.",
  "Friends joke with one another. 'Hey, you're poor.' 'Hey, your mama's dead.' That's what friends do.",
  "I am running away from my responsibilities. And it feels good.",
  "Saw Inception. Or at least I dreamt I did.",
  "Learn how to take off a woman's bra: You just twist your hand until something breaks.",
  "I love my employees even though I hit one of you with my car.",
  "I would not miss it for the world. But if something else came up, I would definitely not go.",
  "This is our receptionist, Pam. If you think she's cute now, you should have seen her a couple years ago.",
  "Like right here is my favorite New York pizza joint. And I'm going to go get me a New York slice.",
  "Nobody likes beets, Dwight! Why don't you grow something that everybody does like? You should grow candy.",
  "It takes you thirty seconds to brush your teeth? Wow, that's ten times as long as it takes me.",
  "Hi, I'm Date Mike. Nice to meet me. How do you like your eggs in the morning?",
  "I've got to make sure that YouTube comes down to tape this.",
  "OK, too many different words from coming at me from too many different sentences.",
  "The people that you work with are, when you get down to it, your very best friends.",
  "Webster's Dictionary defines wedding as 'the fusing of two metals with a hot torch.'",
  "Pizza: the great equalizer.",
  "I am Michael, and I am part English, Irish, German, and Scottish… sort of a virtual United Nations.",
  "If you don't like it, Stanley, you can go to the back of the bus, or the front of the bus, or drive the bus.",
  "My mind is going a mile an hour.",
  "It's a pimple, Phyllis. Avril Lavigne gets them all the time, and she rocks harder than anyone alive.",
  "Is there something besides 'Mexican' you prefer to be called? Something less offensive?",
  "It just seems awfully mean. But sometimes, the ends justify the mean.",
  "Here it is, heart of New York City, Times Square… named for the good times you have when you're in it.",
  "You will not die! Stanley! Stanley! Barack is President! You are black, Stanley!",
  "Well, well, well, how the turntables.",
  "We're all homos. Homo… Sapiens.",
  "You cheated on me? When I specifically asked you not to?",
  "Hate to see you leave, but love to watch you go. 'Cause of your butt.",
  "Well, happy birthday, Jesus. Sorry that your party's so lame.",
  "It's a good thing Russia doesn't exist anymore.",
  "Do you think that doing alcohol is cool?",
  "I hate so much about the things you choose to be.",
  "It's simply beyond words. It's incalculable.",
  "That's what she said!",
  "It's never too early for ice cream.",
  "When I discovered YouTube, I didn't work for five days.",
  "Occasionally, I'll hit someone with my car. So sue me.",
  "I saved a life — my own.",
  "That has sort of an oaky afterbirth.",
  "I have cause. It's beCAUSE I hate him.",
  "I'm not usually the butt of the joke. I'm usually the face of the joke.",
  "You are as creepy as a real serial killer. For real.",
  "You all took a life here today. You did. The life of the party.",
  "Last, and possibly least, you didn't think we'd forget, 'That's what she said!'",
  "Dwight, you ignorant slut!",
  "You miss 100 percent of the shots you don't take. Wayne Gretzky.",
  "I… declare…. bankruptcy!",
  "It's Britney, bitch.",
  "You don't know me, you've just seen my penis.",
  "Jim and I are great friends. We hang out a ton, mostly at work.",
  "The only time I set the bar low is for limbo.",
  "Don't ever, for any reason, do anything to anyone, for any reason, ever, no matter what.",
  "It takes an advanced sense of humor. I don't expect everyone to understand.",
  "I'm not gonna cry over it. I did that in the car on the way home.",
  "The only thing that could make this day better is ice cream.",
  "Those things are like ticking time bags. Alright? Think about it.",
];


export const deadpool: string[] = [
  "You can't buy love, but you can rent it for three minutes!",
  "Okay guys, I only have twelve bullets, so you're all going to have to share!",
  "I didn't just get the cure to el cancer, I got the cure to el everything.",
  "Are you there God? It's me, Margaret!",
  "You look familiar, did I spin you like a beanie propeller and leave you in a motel room in Dubuque?",
  "Sorry, I use humor to deflect my insecurities. Plus, I'm hilarious, so don't hate.",
  "Yeah. That is a gun in my pants. But that doesn't mean I'm not happy to see you…",
  "WAIT! You may be wondering why the red suit. Well, that's so bad guys don't see me bleed.",
  "Life is an endless series of train-wrecks with only brief, commercial-like breaks of happiness.",
  "You don't need to be a superhero to get the girl, the right girl will bring out the hero in you.",
  "I do not hate everything about the world. Just every show they've ever put on after 'Friends'.",
  "What's a nice place like you doing in a girl like this?",
  "Your crazy matches my crazy. Big time.",
  "I just want to get to know the real you. Not the short, 2-dimensional sex object peddled by Hollywood.",
  "I swear to God, I'm gonna find you in the next life, and I'm gonna boombox Careless Whisper outside your window. Wham!",
  "Love is a beautiful thing. When you find it, the whole world smells like a daffodil daydream.",
  "Never underestimate the stupidity of idiots.",
  "I want you to know that I love you very much. I also buried 1,600 kilos of cocaine somewhere in the apartment - right next to the cure for blindness.",
  "I want to die a natural death at the age of 102 - like the city of Detroit.",
  "Gonna eat till I'm tired and then sleep till I'm hungry.",
  "If that hit you in the chest, I'm sorry. I was aiming for your crotch.",
  "Life is an endless series of train-wrecks with only brief, commercial-like breaks of happiness.",
  "Zippty do dah, zippty-ay, I'm gonna blow all you dirtbags away. Plenty of bullets I'm gonna spray, Zippty do dah, zippty-ay.",
  "I can say Chimichanga in seven languages.",
  "With great power comes great merchandising opportunity",
  "Love is a beautiful thing. When you find it, the whole world smells like a daffodil daydream.",
  "I had another Liam Neeson nightmare. I kidnapped his daughter and he just wasn't having it.",
  "You don't need to be a superhero to get the girl, the right girl will bring out the hero in you.",
  "Looks ARE everything. You ever heard David Beckham speak? It's like he mouth-sexed a can of helium.",
  "A-Poc-Key-Lips. I think I found my new favorite word!",
  "My common sense is tingling.",
  "It reeks like old lady pants in here.",
  "Stupid life-stealing homage butthead!",
  "I'd sing some Black Sabbath right now, but the bean counter says we spent all our money on writers. What a waste.",
  "Daddy needs to express some rage.",
  "You just killed the nice deranged chick from the juice bar that I was gonna score with someday maybe!",
  "Crime's the disease, meet the cure. Okay, not the cure, but more like a topical ointment to reduce the swelling and itch.",
  "It's Christmas day, and I'm after someone on my naughty list!",
  "S'matter Buddy? You look a little - what's the word I'm looking for here - stupid.",
  "You're as American as Mom's apple pie and hand guns.",
  "You mean... I'm losing my uncanny knack to tell the Olsen twins apart?",
  "And that is why you never eat a raw starfish, it's just common sense."
]